### ISSUE TITLE
Failed to upgrade Bitwarden from 1.16.1 to 1.16.3 with YunoHost web admin.

### ISSUE THREAD

**Issue by omarechal** [YunoHost-Apps/bitwarden_ynh#102]
--- 

### Describe the bug

Could not upgrade bitwarden. 

### Context

- Hardware: OVH Public Cloud.
- YunoHost version: 4.0.8.3
- I have access to my server: Through SSH & through the webadmin
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no
- Using, or trying to install package version/branch: trying to upgrade Bitwarden from 1.16.1 to 1.16.3
- If upgrading, current package version: 1.16.3

### Steps to reproduce
Upgrading throug web admin. Working for system and all others apps but not for Bitwarden.

### Expected behavior:
Should upgrade from 1.16.1 to 1.16.3.

### Logs

https://paste.yunohost.org/raw/famutacofa

**Comment by yalh76** [comment]
Hi, 

Your upgrade fail because there's already a backup named `bitwarden-pre-upgrade2.tar.gz`.

You will find in `/home/yunohost.backup/archives` two files : `bitwarden-pre-upgrade2.tar.gz` and `bitwarden-pre-upgrade2.info.json`

You should download them before removing them and retry to upgrade :)

**Comment by omarechal** [comment]
Thanks a lot, problem has been solved as per your advice.
Best wishes for 2021!
